### ISSUE TITLE
Generator allocation

### ISSUE THREAD

**Issue by mnm-matin** [pypsa-meets-earth/pypsa-earth#10]
We need a bus_id

To Do:
- If a substation is within 10km than connect to substation and retrieve bus_id
- If not, than handle as a substation and connect to the next line (see substation script). Create a new bus_id on the line.

**Comment by pz-max** [comment]
Allocation of generators happens with K-D Tree approach. **In simple words, generators are connected to the closest bus in the base_network (assigned with its bus_id).** This happens in the PyPSA-Eur rule [built_powerplants](https://github.com/PyPSA/pypsa-eur/blob/b8a76859317d26ca9b8189ef2ee5db21380e83a7/scripts/build_powerplants.py). So as long as we get the generators in the same format as powerplantmatching, allocating them to the right bus should not be a problem.

@koen-vg you could also think about adding the OSM generators which we extracted [here as CSV](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main/data_exploration/data). You can find the [source code for that extraction here](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/data_exploration/osm_pbf_power_data_extractor.py), if you want to make adjustments.


K-D Tree applied in PyPSA-Eur for allocating powerplants to the nearest bus:
` 

                for c in countries:
                substation_i = n.buses.query('substation_lv and country == @c').index
                kdtree = KDTree(n.buses.loc[substation_i, ['x','y']].values)
                ppl_i = ppl.query('Country == @c').index
                tree_i = kdtree.query(ppl.loc[ppl_i, ['lon','lat']].values)[1]
                ppl.loc[ppl_i, 'bus'] = substation_i.append(pd.Index([np.nan]))[tree_i]

 `

**Comment by koen-vg** [comment]
I agree we should follow the PyPSA-Eur approach, which should be easy enough when we have a clean powerplant database from powerplantmatching. See also #37 for integrating the openstreetmap data with other powerplant data.
