### ISSUE TITLE
Line allocation

### ISSUE THREAD

**Issue by mnm-matin** [pypsa-meets-earth/pypsa-earth#11]
To DO:
- separate voltage
- under construction info
- Create bus_id -> start & end
- Line ID
- DC (links) and AC line separation (Transformer in between & station at the location)
- Intersecting lines should join?
- Line changes voltage -> transformer in between
- Line end and start should be a bus

- Big point. Connect all the loose lines (create one network?)

**Comment by pz-max** [comment]
Moved discussion to #22 with updated knowledge.

Our strategy for now:
------------------------------
- create network from available data (make base_network.py work)
- add interconnection plans
- add search heuristic to better plan new connection opportunities
