### ISSUE TITLE
Folium or alternative to create dynamic/interactive plot

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#16]
Plotted the PyPSA-Eur 'base_network.py' inputs [here](https://github.com/pypsa-meets-africa/pypsa-africa/blob/55be90c7c2576a212cc318f2c9bc2b304ae3d245/data_exploration/WP5%20-%20Transmission%20assets/PyPSA_GridKit_Data_Plot.ipynb). Creating static plots is good, but dynamic plots even better. With dynamic plots, I mean that you can zoom in and out and move around the map which is not only useful for detailed data exploration at various locations but also beneficial for future analysis.

The above script already builds in a dynamic plot via Folium. However, slightly more effort should be put into this such that multiple assets can be plotted in one map with different colours. 

Further, one can put some thought into it how all plots in PyPSA could be dynamic i.e. n.plot('dynamic = True')

**Comment by fneum** [comment]
Have you checked out n.iplot() which uses plotly to create a dynamic plot? It has some performance issues, but maybe these could be fixed.

**Comment by pz-max** [comment]
We will have a look. Thanks for sharing @fneum 

Update. The PyPSA **plotly** script looks pretty cool! See [here](https://pypsa.org/examples/scigrid-lopf-then-pf-plotly.html).
There are indeed some performance issues. [Here is a way to optimise the performance.](https://www.somesolvedproblems.com/2018/07/how-do-i-make-plotly-faster.html)

**Comment by mnm-matin** [comment]
Could possibly use Leaflet Vector Grid, see following link for a javascript version
https://gis.stackexchange.com/questions/341648/big-polyline-with-leaflet

**Comment by pz-max** [comment]
Leaflet Vector Grid looks extremely promising as it seems to handle millions of data points with ease! Leaflet will be also used in future as geopandas module see [https://github.com/martinfleis/geopandas-view](https://github.com/martinfleis/geopandas-view)

Suggestion of how to proceed:
1. Try to optimise PyPSA and plotly with the above methods.
2. If performance issue are still there, check out promising leaflet vector grid solution

**Comment by mnm-matin** [comment]
See latest commit with simplified lines. Would have to test whether it alleviates some of the performance issues.

**Comment by pz-max** [comment]
Thanks @Nayara2020 pointing out to [Leafmap](https://leafmap.org/) as alternative

**Comment by fneum** [comment]
Worked on an interactive PyPSA-Eur-Sec dashboard based on hvPlot, holoviews, panel:

https://hvplot.holoviz.org/

Very easy to use, performant and comprehensive (xarray, pandas, geopandas, networkx etc). Can recommend.

Just replace `df.plot()` with `df.hvplot()` to get interactive plot.

I think this is what we'll be using over in "Europe" :)

### Example

```py
import pandas as pd
import hvplot.pandas

df = pd.read_csv(
    "https://raw.githubusercontent.com/FRESNA/powerplantmatching/master/matched_data_red.csv",
    index_col=0
)

df.hvplot.points(
    'lon',
    'lat',
    geo=True,
    frame_height=750,
    c='Fueltype',
    size=df["Capacity"] / 5,
    alpha=0.4,
    tiles='CartoLight',
    hover_cols=['Name', 'Fueltype', "Technology", 'YearCommissioned', "Retrofit", "Capacity"],
    xlim=(-12,32),
).opts(
    active_tools=['pan', 'wheel_zoom']
)
```
