### ISSUE TITLE
Further documentation on data required by pypsa is required for further development

### ISSUE THREAD

**Issue by mnm-matin** [pypsa-meets-earth/pypsa-earth#22]
This has been discussed many times but I think a document explaining how the fields in the csv files produced by entsoegridkit are related should be created. In other words: what rules are followed for the relation of generator_id, bus_id, bus_0, bus_1, etc.

An explanation to the format of the "tags" would also be helpful eg.  "'""TSO""=>"""""

Some geometries are listed as " ""oid""=>""29894""" (ArcGis?) although value such as POINT(39.673004 22.086912) are given in later fields without headers.

It is also important to keep in mind the format of the osm data. We currently have generators, substations and lines only.

**Comment by pz-max** [comment]
@mnm-matin can provide the link to the file?

**Comment by mnm-matin** [comment]
which file?

**Comment by pz-max** [comment]
> which file?

Which document/document is unclear (line.csv, bus.csv, etc.)? We have an explanation of the gridkit stuff [here](https://github.com/PyPSA/pypsa-eur/tree/master/data/entsoegridkit). The described format is the final format we require to make the base_network.py run.

The 'tags' are not directly necessary for us. But just for understanding:
TSO means "transmission system operator"
oid means "object identifier"

You can also use the input data for the base_network.csv (which is provided [here](https://github.com/pypsa-meets-africa/pypsa-eur-playground/tree/master/data/entsoegridkit)) and run the base_network in a jupyter script. I did that [here](https://github.com/pypsa-meets-africa/pypsa-eur-playground). The recording from our first code meeting will help to apply that successfully.

**Comment by mnm-matin** [comment]
Thanks for linking the gridkit stuff and the jupyter notebook. However, there are buses, lines, links, generators and transformers in gridkit. We only have substations (which can have multiple buses), lines and generators. We are mainly missing links and transformers which is not a problem. The relations still need to be described.

The following rules must be satisfied (please correct this if necessary):

-  Each station_id can have one or more associated bus_id
-  Each line_id must have two associated bus_id (bus0 and bus1)
-  Each generator_id must have one associated bus_id

However, we do not have transformers so:
- Each station_id must have strictly one associated bus_id (i.e they are equal)

Not having links doesn't have an affect.

This means we have to:
- snap stations to lines
- generate synthetic stations (joints) between lines
- snap generators to stations

**Comment by pz-max** [comment]
Good comments! Think I get it now. First of all, we focus on making the base_network.py script work. Let me elaborate on your list below:

- #### Each station_id can have one or more associated bus_id.
Yes, a station refers to a substation that is a facility to control power. They normally contain one or more transformers to increase or decrease the voltage, and are linked to the rest of the network by lines or cables. While the bus_id is unique in the substation list, the station_id can appear multiple times). If you search for "48" in the transformer, bus, line dataset you can see that 3 x buses_ids are connected to station_id 48. Each of the buses is related to each other by transformers_id which relates i.e. bus A to bus B to indicate a voltage step up or down.
- #### Each line_id must have two associated bus_id (bus0 and bus1)
Correct. A line has a beginning and an end. The bus0 at one location connects to bus1 at a different location, though be aware that both buses require the same voltage & frequency to be connected (if the frequency changes, there must be a converter; if AC becomes DC vv., there must be a converter; if the voltages are different there must be a transformer)
- #### Each generator_id must have one associated bus_id
Generators are **not** a part of the base_network.py script. But FYI, they are allocated in another script by a distance matrix and receive the bus_id of the closest one.

#### However, we do not have transformers so:
FYI, OpenStreetMap has also a transformer dataset https://wiki.openstreetmap.org/wiki/Tag%3Apower%3Dtransformer. But I would prefer deriving the transformer from the available line and bus data. I guess, we can do that with several functions which would explode this thread but in general the function depends on the voltage, frequency, and location of lines and buses
#### Each station_id must have strictly one associated bus_id (i.e they are equal)
Yes. A station needs at least one bus (I guess, some cases are line endings or substations which connects to equal voltage lines)
#### Not having links doesn't have an affect.
Links are DC lines. They have also a starting and end point and are connected to stations via a converter. As the gridkit dataset provides only 3 converters, I guess they might also derive the converters somehow in the base_network script. But yes, lets connect maybe AC lines first.

#### This means we have to:

- #### snap stations to lines
Yes, if you mean via shapely or the article technique. Think this station needs that at least one unique bus_id (multiple if voltage, frequency or AC/DC changes) & exactly one station_id.
- #### generate synthetic stations (joints) between lines
No. Only 1 unique station_id if lines cross, but multiple buses possible.
1) Every line at **one** specific voltage has a unique bus1 and bus0 number. If two different lines have the bus0/bus1 at the same location -> create station_id.
2) If there is only one unique bus_id at one location (line ending), create station_id
- #### snap generators to stations
No. As above described no necessary.

**Comment by mnm-matin** [comment]
Thanks!
