### ISSUE TITLE
Problems in extraction script

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#24]
The script seems to runs now, though a couple of non-critical problems appear. Maybe good to solve them.

Problems
-------------
- Unable to import 'iso_country_codes'
- Instance of 'BaseGeometry' has no 'x' member; maybe 'xy'?
- Instance of 'BaseGeometry' has no 'y' member; maybe 'xy'?
 
Warnings
--------------
- Import "iso_country_codes" could not be resolved
- Unused variable 'df_node'

**Comment by mnm-matin** [comment]
Seems like an environment issue. Best!
