### ISSUE TITLE
Retrieving 'cable' by osm_pbf_power_data_extractor

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#27]
So far we have the OpenStreetMap (OSM) power.line dataset which represents overhead lines.
We could add OSM [power.cable](https://wiki.openstreetmap.org/wiki/Tag:power%3Dcable) data to our dataset to add underground/oversea lines. Such underground/oversea lines are also implemented in PyPSA-Eur.

**Comment by mnm-matin** [comment]
Yes! I think this would be a good thing to do as a priority. Are you working on this?

Ps. would be great if we could incorporate a measure of priority in our todos

**Comment by pz-max** [comment]
Will implement it tonight :)

Adding a priority is possible in our project board, either by:
- Sorting backlog/to do in top-down sequence from high to low prio
- Using colour card red (high), orange (medium), green (low prio)
