### ISSUE TITLE
Data Cleaning need to be added to new script

### ISSUE THREAD

**Issue by mnm-matin** [pypsa-meets-earth/pypsa-earth#28]
See TODO comments in cleaning scripts. Would have to refine and add rules for cleaning inclusive of comments.

**Comment by pz-max** [comment]
Are you talking about the osm_data_cleaning.py script? If so, you have to push the comments. 
Should we maybe make first the jupyter run perfectly before making the cleaning script?

**Comment by mnm-matin** [comment]
Just confirmed the TODO: comments are present as a placeholder in the script. Absolutely, let's craft the rules in the jupyter notebook first. Best!

**Comment by mnm-matin** [comment]
@pz-max linting can really only be enforced once we have decided on a formatting standard for the code base. Best!

**Comment by pz-max** [comment]
Guess sticking to the super-linter suggestions should be fine for now. 
Its a learning experience and leads to more homogenous code
