### ISSUE TITLE
Expand OSM power extractor tool to the world

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#29]
For now, we extract OpenStreetMap data only for Africa in our [osm_pbf_power_data_extractor.py](https://github.com/pypsa-meets-africa/pypsa-africa/blob/4e66c44a871eb68d98a7f0ab0dc4ad8e2d654b46/data_exploration/WP5_transmission_assets/osm_pbf_power_data_extractor.py). 

Because we want to apply some ML to detect energy assets (and because it would be just a great feature for the community), we need to add all other continents to the extraction process. You might to adjust the [iso_country script](https://github.com/pypsa-meets-africa/pypsa-africa/blob/4e66c44a871eb68d98a7f0ab0dc4ad8e2d654b46/scripts/iso_country_codes.py) to exclude countries that represent small islands.

That script should be operatable from a list i.e. ["Africa", "Europe", "Asia","Islands"]

**Comment by mnm-matin** [comment]
The following might be relevant:
[pyrosm geofabrik file](https://github.com/HTenkanen/pyrosm/blob/master/pyrosm/data/geofabrik.py)

**Comment by pz-max** [comment]
Closed by commit https://github.com/pypsa-meets-africa/pypsa-africa/commit/c966ad42b5e477a2a3821f5317a0191afaaad59a
