### ISSUE TITLE
Create "powernetworkmatching" similar to "powerplantmatching"

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#33]
Comparing the [OSM_extracted network map](https://github.com/pypsa-meets-africa/pypsa-africa/blob/4e66c44a871eb68d98a7f0ab0dc4ad8e2d654b46/data_exploration/WP5_transmission_assets/img/africa_powermap.png) to the [worldbank provided map](https://github.com/pypsa-meets-africa/pypsa-africa/blob/4e66c44a871eb68d98a7f0ab0dc4ad8e2d654b46/data_exploration/WP5_transmission_assets/img/africa_transmission_and%20substations_110.png), we could see that mixing both datasets would be best (check Egypt and Mauritania). So maybe it would make sense to combine these datasets without adding duplicates if possible.

**Comment by mnm-matin** [comment]
Both maps are osm_extrated maps.

**Comment by pz-max** [comment]
Buses probably from OSM but lines came from the Onsset/worldbank dataset. More details on the data are given here: https://github.com/pypsa-meets-africa/pypsa-africa/blob/new-main/notebooks/old%20notebooks/OLD___HV_network.ipynb

**Comment by mnm-matin** [comment]
You're right. Thanks! Seems like the osm_extracted map had some cleaning on the lines as well. Can you say for certain that the datasets are different?

**Comment by pz-max** [comment]
If you open the Jupyter script https://github.com/pypsa-meets-africa/pypsa-africa/issues/33#issuecomment-891922038 and read the "copied" data description it seems worldbank opened some additional archives or used some extra resources. I think its probable that they shared some data that is not in the OSM dataset.

We need to check how we filtered according to the voltage both datasets and then compare them. But just have a look at Egypt & Mauritania. Guess it's highly likely that these datasets differ to a degree.

**Comment by davide-f** [comment]
This is an interestign point, though not sure if it's worth keeping it open.

**Comment by pz-max** [comment]
Yep, I think improving OSM is much better invested time!
Let's close because this task is also not trivial
