### ISSUE TITLE
Everything Wrong with osm_pbf_power_data_extractor.py

### ISSUE THREAD

**Issue by mnm-matin** [pypsa-meets-earth/pypsa-earth#35]
The script works fine but there are some areas of improvements which I will list in this issue. There are various TODO: comments scattered throughout the code as well.
- [x] Empty dataframes i.e. for lines, cables, generators, buses currently lead to a bug in the conversion from the pd dataframe to the geoJSON. A check if the dataframe is empty needs to be performed.
- [x] Logging needs to be enabled. Some logging code is commented out. Some other errors and statements are printed to console instead of logger.
- [x] update argument need to be propagated to the main function and ideally be added as an arg to the script. See download_pbf and download_and_filter where update=false. Also relevant is checking the downloaded pbf files with a corresponding file size to ensure data is not corrupted during the download.
- [x] In download_and_filter function the feature_data should be extracted in a pythonic generator and yield way. This would also allow for a config to include/exclude certain features. A complete list of power features is given [here on osm ](https://wiki.openstreetmap.org/wiki/Key:power). This should also massively reduce the code duplication that can be seen in various functions where we loop over a list of features.
- [x] In convert_ways_points function: the set_crs and to_crs should be called for the whole lonlat_list and not individually. This was a major performance pitfall as identified using [functionTrace](https://functiontrace.com/)
- [x] convert_ways_points and convert_ways_lines can be combined to reduce code duplication. Separate functions for calculating the area and length would have to be created.
- [x] convert_pd_to_gdf is better refactored as convert_pd_to_gdf_points
- [x] #69

Disclaimer: I have written most of the code in the script and that is why I feel so liberal critiquing it.

**Comment by davide-f** [comment]
I add that in the nigeria only test case, which includes no cables data, the geojson cannot be saved because it would be empty.
The code should account for that, and the cleaning file as well, if you agree.

I wonder if it makes sense to generalize that to also the other files; maybe it is not worthy: a country with no generation, lines or substations does not exist in practical terms, but some data may not be available, but how often does it happen?

**Comment by pz-max** [comment]
Thanks @mnm-matin for the list to keep track of it. Some of the tasks are ideal issues to get started.  :+1: 
For now the priority is to focus on building the model & the extractor script does its function pretty well for now.

@davide-f I think a small check if the df is empty should avoid the error message (like don't try to extract if df is empty). A stackoverflow explanation on how to do it is [here](https://stackoverflow.com/questions/36543606/python-pandas-check-if-dataframe-is-not-empty):
```
if not dataframe.empty:
      #code here
```

This check should be applied for everything that is intended to be converted as GeoJSON. Some countries, especially smaller islands might have no data at all (no lines, cables, generators, substations).

**Comment by davide-f** [comment]
I may be of help, depending on timings and other possible commitments you may have

**Comment by mnm-matin** [comment]
> I add that in the nigeria only test case, which includes no cables data, the geojson cannot be saved because it would be empty.
> The code should account for that, and the cleaning file as well, if you agree.
> 

Yes, absolutely agree that the extract script should handle this. Any changes to the extract script must be followed by a complete run on AFRICA_CC. Doing so would have spotted the bug.

**Comment by mnm-matin** [comment]
Some major updates to the script and to the repo visible in a new branch appropriately named 'new-main' as its going to be the new main. The overall repository is more clean and should be easier to work with.

The extract script now runs with approx 70% less memory usage and is faster by about 5 times due to a critical mistake which meant that the pre-filter process was running every time for every feature. This has been fixed. Code duplication has also been massively reduced. A new dictionary feature_category coupled with a feature list means we can support all power tags now. Md5 checking has been added to verify downloaded pbfs which should make updating files a lot easier. Some other action points still remain, but at this point the focus might be better set on other things in the grand scheme of the project.

**Comment by mnm-matin** [comment]
Issue closed as this script is at a point where I'm happy with it.

**Comment by pz-max** [comment]
Our best script at the moment! 
Well done :1st_place_medal:
