### ISSUE TITLE
Modelling hydro inflow

### ISSUE THREAD

**Issue by koen-vg** [pypsa-meets-earth/pypsa-earth#38]
As we are developing the database of powerplants, we also need to model hydro inflow for all hydro plants. That is, for each hydroplant, we need hourly time series giving the amount of water flowing into the reservoir of the power plant (in MW).

As a first step, we should set up atlite to do this. That's how it's done in PyPSA-Eur, and can serve as inspiration here. The inflow modelling in PyPSA-Eur is quite simple, but is a good starting point. If we want, we can later integrate more advanced hydro-specific tools such as LISFLOOD.

Resources:
- Atlite documentation: https://atlite.readthedocs.io/en/latest/introduction.html
- The paper in JOSS about atlite: https://doi.org/10.21105/joss.03294
- See https://doi.org/10.1016/j.mex.2019.05.024 about the hydro methodology used in atlite. See also refs. https://doi:10.1016/j.energy.2017.06.004, https://doi:10.1016/j.esr.2018.08.012 for how it is used in PyPSA-Eur.

**Comment by davide-f** [comment]
I added an implementation on the function hydro, to be crosschecked
