### ISSUE TITLE
Implement atlite build_cutouts

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#50]
We need timeseries data for solar, wind and hydro. I will try to implement existing Atlite approaches.

**Comment by pz-max** [comment]
**Update.** Cutouts are pretty much implemented and I will push them tomorrow. Recognised issues:
- TODO: PyPSA-Eur environment (which the pypsa-africa one is based on) has not all new bug fixes from Atlite such as the `orography to geopotential` renaming which led to a bug in build_cutout. I fixed the bug according to the new atlite version in my personal envrionment.
- TODO: The `build_shapes` output file and path must be better aligned to the `build_cutout` ones (Quick fix. Just waiting until build shapes is stable)
- INFO: The cutout data for the whole African continent is ~21GB. We store that data in our team cloud and share them later with the crowd once more stable. 
- INFO: Hosting the data is highly recommended! Retrieving the data from the Copernicus website via the API can take a couple of hours up to days depending on where the job is settled in the queue.

**Next steps:**
- build nature_raster
- build renewable_timeseries

**Comment by pz-max** [comment]
@euronion era data could be successful downloaded. I will continue now with the RE timeseries. Could you linger a bit on the difference between the Sarah2 & Era5 data? What is your recommendation of the usage for both?

**Comment by euronion** [comment]
Good job!

In short:
ERA5 is ok for wind time-series, but not so good for solar time-series in some regions.

[Urraca et al (2018)](https://doi.org/10.1016/j.solener.2018.02.059) summarise it nicely:
"[...] This makes **ERA5 comparable** with satellite-derived products in terms of the mean bias **in most inland stations**, but ERA5 **results degrade in coastal areas and mountains.** The bias of ERA5 varies with the cloudiness, overestimating under cloudy conditions and slightly underestimating under clear-skies, which suggests a poor prediction of cloud patterns and leads to larger absolute errors than that of satellite-based products. [...] We conclude that ERA5 and COSMO-REA6 have reduced the gap between reanalysis and satellite-based data, but further development is required in the prediction of clouds while the spatial grid of ERA5 (31 km) remains inadequate for places with high variability of surface irradiance (coasts and mountains). Satellite-based data should be still used when available, but having in mind their limitations, ERA5 is a valid alternative for situations in which satellite-based data are missing (polar regions and gaps in times series) while COSMO-REA6 complements ERA5 in Central and Northern Europe mitigating the limitations of ERA5 in coastal areas."
