### ISSUE TITLE
Proposal for standard raw file for debug purposes

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/pypsa-earth#57]
To avoid issues in the accessibility of resources online (see problems with the gadm platform), we may decide to store a sample of raw data to be internally used as debug.
The sample may be related to 1-2 countries just to run the codes.

To do so, we may enable to push changes of the folder data/raw for example (assuming that will be the one used to store the raw data)

**Comment by mnm-matin** [comment]
happy to exclude (from the gitignore) a test file with a subset of countries , Do you have a good subset of countries in mind that covers most of the data cleaning cases?

**Comment by pz-max** [comment]
Let's maybe pick the 2 countries where most partners are from namely, Nigeria and South Africa.
Further, @Hazemakhalek needs to work on Morroco to align best with his research.
Having at least two countries helps also regarding testing the loops.

Therefore let's go maybe for Nigeria, South Africa and Morroco?

**Comment by hazemful** [comment]
Yes, would be really nice if you can include Morocco too

**Comment by davide-f** [comment]
I suggest that we may create a number of possible cases with different characteristics.

The sets of options shall account for what is the goal and scope of the tool. When we look at the whole africa, I believe some of the criticalities below may not apply, but if (as I believe) the tool is intended to be very flexible, then problems may arise.

Regarding the input data, I see the following list of criticalities, which often lead to the need to manage some empty file:
- when only few small countries are considered, not all information are available, such as "cables", thus not all files may be generated.
- Similarly, when only countries with no access to the ocean are considered, no off_shore zones (and shapes) are available, which leads to another empty file
[others to come]

**Comment by pz-max** [comment]
Absolutely right Davide. A list of suggested countries in the raw file:
- **Morroco**, (has cables) 
- **Niger** (no cables, no offshore areas sea)
- **Nigeria**, (identified interconnector problem)
- **Sierra Leone**, (small country)

Think we can exclude South Africa for now to make life easier.
If the above countries work, there might be no issue with South Africa.

**Comment by davide-f** [comment]
To run the build_shape script with the above, the following is the current files by folder with the organization I proposed:
- data/raw/eez/eez_v11.gpkg
- data/raw/eez/eez_boundaries_v11.gpkg [I don't use it but it doesn't harm]
- data/raw/eez/license_eez_v11.txt [I don't use it but it doesn't harm]
- data/raw/gadm/gadm_36_MAR/gadm_36_MAR.gpkg [it may be useful to enable the subfolder gadm_36_MAR]
- data/raw/gadm/gadm_36_NER/gadm_36_NER.gpkg [it may be useful to enable the subfolder gadm_36_NER]
- data/raw/gadm/gadm_36_NGA/gadm_36_NGA.gpkg [it may be useful to enable the subfolder gadm_36_NGA]
- data/raw/WorldPop/mar_ppp_2020_UNadj_constrained.tif
- data/raw/WorldPop/ner_ppp_2020_UNadj_constrained.tif
- data/raw/WorldPop/nga_ppp_2020_UNadj_constrained.tif
- data/raw/GDP/GDP_PPP_1990_2015_5arcmin_v2.nc
- data/raw/GDP/GDP_PPP_1990_2015_5arcmin_v2.tif [generated by the script]

The package above is about 410-430MB

The results of the build_shapes will be put in resources/... (it is not in gitignore, better so).
For tests with you, I can share some processed files so that you can go on, without the need to run the entire script.
We may start for a small nation; morocco?

**Comment by davide-f** [comment]
For some analyses, having a small country such as Sierra Leone might be useful

**Comment by davide-f** [comment]
I shared the raw data in the onedrive folder and the results of build_shapes for Sierra Leone in github (in pull request)
