### ISSUE TITLE
Fix coordinates obtained from osm filter script

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#7]

**Comment by mnm-matin** [comment]
To Do:
- Centroid correction (high priority)
- 1 station id for bus with two voltages + two different bus id
- Fix substation inference to lines (problem = line id doesnt exist)
- Substations in the sea

**Comment by pz-max** [comment]
Comment:
- Substation in the sea not necessarily bad and can be observed also in [EU](https://www.linkedin.com/posts/maximilian-parzen-b047a1126_africa-ai-energysystems-activity-6804048947812810752-BPcA)

**Comment by mnm-matin** [comment]
I fixed the centroid, there are issues for the other points.
