### ISSUE TITLE
Local variable referenced before content - powerplantmatching 

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#84]
Update, we tested the current version of powerplantmatching in branch WP2. @mnm-matin and I had the following issue:

![image](https://user-images.githubusercontent.com/61968949/131219016-c9d6e8b7-8dc4-41a6-84c8-24d41a48bdde.png)

Further, just a note. It seems that the issue you had with the custom_config is solved (see https://github.com/FRESNA/powerplantmatching/issues/41). As you mentioned in the [README](https://github.com/pypsa-meets-africa/pypsa-africa/blob/22352fca57d16199d805be5bd038222fdef3fcf2/data_exploration/WP2%20-%20Conventional%20generators/README.md) it makes probably sense to use now the less hacky custom_config feature, since the issue is fixed. They are also quite some updates upstream that might remove the above-described issue.

Let us know what are your thoughts or plans :+1:

**Comment by koen-vg** [comment]
Closed by #116
