### ISSUE TITLE
Potential to make package out of osm_extractor, cleaning and build_network script

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#86]
The [osm_pbf_power_data_extractor.py](https://github.com/pypsa-meets-africa/pypsa-africa/blob/new-main/scripts/osm_pbf_power_data_extractor.py) extracts OpenStreetMap data for power lines, cables, substation, cables at the moment. It can be put in an extra repository for the following reason:
- Allow easier usage and separate development
- New osm power features can be extracted with that tool etc.
- Add also more flexible cleaning and network build script

Some thoughts need to put into that as well as some time spent for proper execution.

**Comment by davide-f** [comment]
Closing thanks to #547 <3
