### ISSUE TITLE
power_data_extractor_tool unexpected lines

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/pypsa-earth#89]
When applying the power extractor tool to the whole africa about 100 unexpected lines are saved in the csv.
Such lines may not have buses, or a specific country associated.
In github I push the output file I obtained, which is the most updated, given the scripts

**Comment by pz-max** [comment]
We extract in the extractor tool all the OpenStreetMap data from a given set of countries.
These files are almost not cleaned, hence considered as "raw".
The cleaning script should make sure that these empty columns are removed.
If this does not happen, we should make sure it removes such blanked lines.

Some stuff which might help:
- countries can be easily found by checking in which country the asset is situated (shapely `.contains` function is useful here)
- if a line exists, a bus is created for the start and endpoint of the line in `osm_build_network.py`

**Comment by davide-f** [comment]
Yeah, I agree on the above, but there are some issues.
Some points are far away in the ocean, thus they cannot be easily set in a specific country. That applies for several lines for example, which lead to warnings in build_bus_regions (I discovered it because of that)

**Comment by pz-max** [comment]
Do you ave a plot on these ocean buses?
"Ocean" buses are not necessarily articial. Offshore wind plants are represented by such.
I know that PyPSA-Eur had something like buses["offshore_bus"] = True, that probably dealt with that issue. Maybe we should do smt similar?
________________________________

**Comment by davide-f** [comment]
Exactly, the errors related to the lines are that no buses are linked to those lines. Regarding the buses, I checked the weird coordinates in the raw data.
Now I'm fixing other stuff, as I have time I move there.

**Comment by davide-f** [comment]
I investigated and the output lines to plot are ok, but the main concerns are in the input data.
I think we may have to better investigate the raw input data. For example, no lines are found for Namibia, but if I look at the file NA_lines.json there are several lines.
I am relatively new to the last details of data_extractor (I worked on data cleaning months ago), which is the reason I am highlighting this at a high-level, but maybe some of the missing data that we are experiencing may be solved by investigating that.
P.S. I added some plotting features of the lines in the notebook of bus_regions
What is your feeling?

**Comment by pz-max** [comment]
My feeling is that it’s worth revising the osm_build_network, cleaning an du extraction tool. I also shared yesterday some issue on GitHub describing what goes wrong

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davide-f** [comment]
This issue has been mainly solved by #91; however there are still some smaller inaccuracies. See the plots using the new notebook build_bus_regions_verifybuseslines in the notebook folder.
Now only few lines are not matched: still some work is needed but the main problem (related to Namibia) is solved.

**Comment by davide-f** [comment]
I close this issue as it has been solved by #96
