### ISSUE TITLE
Add Climate compatible growth techno-economic data

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#9]
[Climate compatible growth](https://www.climatecompatiblegrowth.com/starter-kits/) is providing a documented dataset for each each country in Africa.

Some of their data is useful for our project, for instance, capital cost, variable cost, discount rates, average capacity factors for non-variable generators. This data is provided also per country over the lifetime from 2015-2050.

One task would be to create a dataframe from the above data that looks like [PyPSA-Eur](https://github.com/PyPSA/pypsa-eur/blob/master/data/costs.csv). Just for multiple years and a new column called 'country'.

**Comment by davide-f** [comment]
Old issue; #459 contains more recent considerations aligned with current status

**Comment by pz-max** [comment]
> 
With Climate Compatible Growth (CCG) we referred to the OSeMOSYS modelkit data.
After quickly scanning it, it seems not very useful and flexible. Closing this issue is therefore fine.
